name: Builder

on: [workflow_dispatch]

jobs:
  build-application:
    runs-on: "ubuntu-latest"

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v4

      - name: Installing Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build
